In [2]:
import numpy as np
import pandas as pd

# 배열의 정보를 확인하기 위한 함수 정의

def aryInfo(ary) :
    print('type - ', type(ary))
    print('shape - ', ary.shape)
    print('dimension - ', ary.ndim)
    print('dtype - ', ary.dtype)
    print()
    print('data - ')
    print(ary)

- 배열 연결(concatenate)
- hstack(), vstack(), dstack(), r_, c_, tile

In [4]:
print('hstack - 행의 수가 같은 두 개 이상의 배열을 연결')

ary01 = np.ones((3,4))
print(ary01)
ary02 = np.zeros((3,5))
print(ary02)
print()

print(np.hstack([ary01, ary02]))

hstack - 행의 수가 같은 두 개 이상의 배열을 연결
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0.]]


In [5]:
print('vstack - 열의 수가 같은 두 개 이상의 배열을 연결')

ary01 = np.ones((3,4))
print(ary01)
ary02 = np.zeros((3,4))
print(ary02)
print()

print(np.vstack([ary01, ary02]))

vstack - 열의 수가 같은 두 개 이상의 배열을 연결
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
print('dstack - 행과 열이 아닌 깊이 방향으로 배열을 연결')
# 반드시 행과 열이 같아야 한다
ary01 = np.ones((3,4))
print(ary01)
ary02 = np.zeros((3,4))
print(ary02)
print()

print(np.dstack([ary01, ary02]))

dstack - 행과 열이 아닌 깊이 방향으로 배열을 연결
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]


In [10]:
print('stack - 사용자가 지정한 차원(축: x, y) 배열을 연결')
# 축 방향: axis = 0 default
ary01 = np.ones((3,4))
print(ary01)
ary02 = np.zeros((3,4))
print(ary02)
print()

print(np.stack([ary01, ary02]))
print(np.stack([ary01, ary02], axis=1))

print()
aryInfo(np.stack([ary01, ary02]))

stack - 사용자가 지정한 차원(축: x, y) 배열을 연결
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]

type -  <class 'numpy.ndarray'>
shape -  (2, 3, 4)
dimension -  3
dtype -  float64

data - 
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [15]:
print('r_[] - 인덱서 == hstack 열의 증가하는 배열 연결')
print('c_[] - 인덱서 == 배열의 차원증가 후 배열 연결')
print(np.r_[np.array([1,2,3]), np.array([4,5,6])])
print()

print(np.c_[np.array([1,2,3]), np.array([4,5,6])])

r_[] - 인덱서 == hstack 열의 증가하는 배열 연결
c_[] - 인덱서 == 배열의 차원증가 후 배열 연결
[1 2 3 4 5 6]

[[1 4]
 [2 5]
 [3 6]]


In [17]:
print('tile - 동일한 배열을 반복하여 연결')
ary = np.array([[1,2,3],[4,5,6]])
aryInfo(ary)
print()
print(np.tile(ary, (3,3)))

tile - 동일한 배열을 반복하여 연결
type -  <class 'numpy.ndarray'>
shape -  (2, 3)
dimension -  2
dtype -  int32

data - 
[[1 2 3]
 [4 5 6]]

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]


In [38]:
# 위 결과가 나올 수 있도록 함수를 이용하여 작성해 보세요~~~
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])

ary01 = np.zeros((3,3))
ary02 = np.ones((3,2))
ary_hstack = np.hstack([ary01, ary02])
ary03 = np.arange(10,160,10).reshape(3,5)
ary_vstack = np.vstack([ary_hstack, ary03])
answer = np.tile(ary_vstack, (2,1))
print(answer)

[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


#### delete()
- axis 기준행과 열을 삭제할 수 있다: axis = 0(행), 1(열)
- axis 지정하지 않으면 1차원 변환 후 삭제
- 원본배열을 변경하지 않고 새로운 배열 return

In [44]:
ary = np.random.randint(0,10, (3,4))
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (3, 4)
dimension -  2
dtype -  int32

data - 
[[9 8 5 9]
 [1 9 5 3]
 [3 2 0 0]]


In [46]:
ary_new = np.delete(ary, 1, axis = 1)
aryInfo(ary_new)

type -  <class 'numpy.ndarray'>
shape -  (3, 3)
dimension -  2
dtype -  int32

data - 
[[9 5 9]
 [1 5 3]
 [3 0 0]]


- loadtxt() : 파일 입출력 가능

In [52]:
raw_data = np.loadtxt('./data/numpy_data/02. crime_in_Seoul.csv',
                     dtype = np.object,
                     skiprows = 1)
aryInfo(raw_data)
print()

print(raw_data[0])
print()

ary = raw_data[ : , np.newaxis]
aryInfo(ary)
print()

ary[0][0]

type -  <class 'numpy.ndarray'>
shape -  (31,)
dimension -  1
dtype -  object

data - 
['중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170"'
 '종로서,3,3,6,5,115,98,"1,070",413,"1,278","1,070"'
 '남대문서,1,0,6,4,65,46,"1,153",382,869,794'
 '서대문서,2,2,5,4,154,124,"1,812",738,"2,056","1,711"'
 '혜화서,3,2,5,4,96,63,"1,114",424,"1,015",861'
 '용산서,5,5,14,14,194,173,"1,557",587,"2,050","1,704"'
 '성북서,2,2,2,1,86,71,953,409,"1,194","1,015"'
 '동대문서,5,5,13,13,173,146,"1,981",814,"2,548","2,227"'
 '마포서,8,8,14,10,294,247,"2,555",813,"2,983","2,519"'
 '영등포서,14,12,22,20,295,183,"2,964",978,"3,572","2,961"'
 '성동서,4,4,9,8,126,119,"1,607",597,"1,612","1,395"'
 '동작서,5,5,9,5,285,139,"1,865",661,"1,910","1,587"'
 '광진서,4,4,14,26,240,220,"3,026","1,277","2,625","2,180"'
 '서부서,2,2,2,1,70,59,819,293,"1,192","1,038"'
 '강북서,7,8,14,13,153,126,"1,434",618,"2,649","2,348"'
 '금천서,3,4,6,6,151,122,"1,567",888,"2,054","1,776"'
 '중랑서,13,12,11,9,187,148,"2,135",829,"2,847","2,407"'
 '강남서,3,3,15,12,300,225,"2,411",984,"2,465","2,146"

C:\Users\user\AppData\Local\Temp\ipykernel_29336\848983900.py:2: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype = np.object,


'중부서,2,2,3,2,105,65,"1,395",477,"1,355","1,170"'

#### 배열의 연산
- vectorized operator(벡터화 연산)
- 브로드 캐스팅: 벡터와 행렬의 연산을 위해서는 크기가 같아야 한다.

In [53]:
ary01 = np.arange(1, 10001)
ary02 = np.arange(10001, 20001)

In [54]:
%%time
result = np.zeros_like(ary01)
for idx in range(len(ary01)) :
    result[idx] = ary01[idx] + ary02[idx]
    
print('answer')
print(result)

answer
[10002 10004 10006 ... 29996 29998 30000]
CPU times: total: 0 ns
Wall time: 6.52 ms


In [58]:
%%time
result = np.zeros_like(ary01)
result = ary01 + ary02
print('answer')
print(result)

answer
[10002 10004 10006 ... 29996 29998 30000]
CPU times: total: 0 ns
Wall time: 980 µs


In [59]:
ary01 = np.array([1,2,3,4])
ary02 = np.array([4,2,2,4])
ary03 = np.array([1,2,3,4])
print()
print('배열의 모든 원소가 같은지를 비교하고 싶다면? - all()')
np.all(ary01 == ary02)


배열의 모든 원소가 같은지를 비교하고 싶다면? - all()


False

In [66]:
ary = np.arange(5)
ary * 1

array([0, 1, 2, 3, 4])

In [67]:
ary01 = np.arange(12).reshape(-1,4)
ary01

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
ary02 = np.arange(3)
ary02

array([0, 1, 2])

In [69]:
ary01 + ary02[ : , np.newaxis]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

#### 차원축소(dimension reduction)
- 기술적 통계함수(min, max, sum, mean, median, std, var etc...)
- all, any
- 인덱스를 리턴하는 차원축소 함수: argmin, argmx

In [71]:
ary = np.array([1,2,3,4,5])
print('data - ', ary, ary.shape, ary.ndim)
print('sum - ', np.sum(ary), type(np.sum(ary)))
print('sum - ', ary.sum(), type(ary.sum()))
print()

print('min - ', np.min(ary), type(np.min(ary)))
print('min - ', ary.min(), type(ary.min()))
print()

print('max - ', np.max(ary), type(np.max(ary)))
print('max - ', ary.max() , type(ary.max()))
print()

print('mean - ', np.mean(ary), type(np.mean(ary)))
print('mean - ', ary.mean(), type(ary.mean()))
print()

print('median - ', np.median(ary), type(np.median(ary)))
#print('median - ', ary.edian(), type(ary.median())) - error


data -  [1 2 3 4 5] (5,) 1
sum -  15 <class 'numpy.int32'>
sum -  15 <class 'numpy.int32'>

min -  1 <class 'numpy.int32'>
min -  1 <class 'numpy.int32'>

max -  5 <class 'numpy.int32'>
max -  5 <class 'numpy.int32'>

mean -  3.0 <class 'numpy.float64'>
mean -  3.0 <class 'numpy.float64'>

median -  3.0 <class 'numpy.float64'>


In [73]:
ary = np.array([1,2,3,4,5])
ary
print('index - ', np.argmin(ary))
min_idx = np.argmin(ary)
print('min_idx - ', min_idx, ary[min_idx])
print('index - ', np.argmax(ary), ary[np.argmax(ary)])

index -  0
min_idx -  0 1
index -  4 5


In [74]:
print('all - ')

print('any - ')

all - 
any - 


- 연산의 대상이 2차원 행렬(matrix)이라면?
- axis 방향 설정이 중요

In [76]:
ary = np.arange(1, 21, 1).reshape(4, -1)
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (4, 5)
dimension -  2
dtype -  int32

data - 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [78]:
print('sum - ')
print('sum - ', np.sum(ary), type(np.sum(ary)))
print('row sum - ', np.sum(ary, axis=1), type(np.sum(ary, axis = 1)))
print('col sum - ', np.sum(ary, axis=0), type(np.sum(ary, axis = 0)))

sum - 
sum -  210 <class 'numpy.int32'>
row sum -  [15 40 65 90] <class 'numpy.ndarray'>
col sum -  [34 38 42 46 50] <class 'numpy.ndarray'>


In [ ]:
print('min, argmin - index, max argmax - index, mean, median')

In [82]:
print(np.min(ary, axis=1))
print(np.min(ary, axis=0))

[ 1  6 11 16]
[1 2 3 4 5]


In [89]:
ary = np.random.randint(0, 100000, (5,6))
ary

array([[17435, 57596, 81354, 95292, 13609,  8224],
       [42359, 16781, 91535, 40234, 57237, 64417],
       [43623, 57379, 88568, 91074, 37249, 82627],
       [54874, 14044, 70441, 40360, 26004, 19423],
       [90039, 26771, 56925, 13692, 83612, 38942]])

In [90]:
print('전체의 최대값 - ', np.max(ary))

전체의 최대값 -  95292


In [91]:
print('전체의 최대값 - ', np.max(ary))
print('행의 합 - ', np.sum(ary, axis = 1))
print('행의 합 for - hstack - ', np.hstack([ary[idx].sum() for idx in range(ary.shape[0])]))

전체의 최대값 -  95292
행의 합 -  [273510 312563 400520 225146 309981]
행의 합 for - hstack -  [273510 312563 400520 225146 309981]


In [92]:
for idx in range(ary.shape[0]):
    print(ary[idx].sum())

273510
312563
400520
225146
309981


In [94]:
print('각 행의 최대값 - ')
print(np.hstack([ary[idx].max() for idx in range(ary.shape[0])]))
print('각 열의 평균 - ', np.mean(ary, axis = 0))
print(np.hstack([ary[:, idx].mean() for idx in range(ary.shape[1])] ))
print('각 열의 최소값 - ')
print(np.hstack([ary[:, idx].min() for idx in range(ary.shape[1])] ))

각 행의 최대값 - 
[95292 91535 91074 70441 90039]
각 열의 평균 -  [49666.  34514.2 77764.6 56130.4 43542.2 42726.6]
[49666.  34514.2 77764.6 56130.4 43542.2 42726.6]
각 열의 최소값 - 
[17435 14044 56925 13692 13609  8224]


- 정렬: sort()
- ary.sort(): 원본에 대한 변경(inplace = True)
- np.sort(ary): 원본에 대한 변경 x (inplace = False)

In [95]:
ary = np.arange(10)
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.random.shuffle(ary)
ary

array([3, 0, 7, 2, 4, 5, 9, 1, 8, 6])

In [97]:
np.sort(ary)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
ary

array([3, 0, 7, 2, 4, 5, 9, 1, 8, 6])

In [99]:
ary.sort()

In [100]:
ary

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.random.shuffle(ary)
ary

array([1, 2, 4, 9, 8, 5, 6, 0, 3, 7])

In [103]:
print('내림차순 - ')
np.sort(ary)[::-1]

내림차순 - 


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [105]:
print('행렬에 대한 정렬 - ')
ary = np.random.randint(0, 17, (4,4))
ary

행렬에 대한 정렬 - 


array([[10, 11,  9,  9],
       [ 4, 16,  8,  7],
       [16,  0,  5,  3],
       [10,  7,  7,  7]])

In [106]:
print('행 정렬 axis = 1')
print(np.sort(ary, axis = 0))

행 정렬 axis = 1
[[ 4  0  5  3]
 [10  7  7  7]
 [10 11  8  7]
 [16 16  9  9]]


- 만약 정렬된 인덱스를 필요로 한다면?
- np.argsort()

In [107]:
ary = np.array([4,3,5,7])
ary

array([4, 3, 5, 7])

In [108]:
ary_idx = np.argsort(ary)
ary_idx

array([1, 0, 2, 3], dtype=int64)

In [109]:
ary[ary_idx][::-1]

array([7, 5, 4, 3])

In [110]:
ary = np.random.randint(1,17,(4,4))
ary

array([[15, 10, 10, 16],
       [15,  8,  6,  2],
       [ 1,  6, 11,  2],
       [ 6, 11, 11, 12]])

In [113]:
ary[0].argsort()

array([1, 2, 0, 3], dtype=int64)

- 연결보다는 행추가 컬럼추가 하는 방법
- np.concatenate()

In [114]:
ary = np.array( [[1,2,3],[4,5,6]])
ary

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
print('행 추가 - ')
new_row = np.array([7,8,9])
np.concatenate((ary, new_row[np.newaxis, : ]), axis=0)
np.concatenate((ary, new_row.reshape(1,3)), axis=0 )

행 추가 - 


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
print('문제 - 200개의 표준정규분포 샘플을 만들어서 내림차순으로 상위 5%까지의 결과를 출력')
ary = np.random.randn(200)
aryInfo(ary)

문제 - 200개의 표준정규분포 샘플을 만들어서 내림차순으로 상위 5%까지의 결과를 출력
type -  <class 'numpy.ndarray'>
shape -  (200,)
dimension -  1
dtype -  float64

data - 
[ 4.72920074e-02 -6.11269712e-01  1.27674531e+00 -1.38717058e+00
 -5.37424018e-01  1.09474586e+00  1.44334839e-01  5.19268495e-01
  2.42555724e+00 -2.16341451e-01 -2.96549923e-01 -1.02931682e-01
 -1.95840561e+00  7.86412878e-01  2.18394152e-01 -1.09626163e-01
 -8.13178283e-02  9.88641218e-01 -8.96755390e-01  9.91103922e-01
  1.44888382e+00  2.39357801e+00  1.40863693e+00 -9.40024199e-01
  2.59043436e+00  3.64690873e-01 -7.58113516e-01 -2.89778033e-01
  5.72912011e-01 -7.68974643e-01  8.43214489e-01 -1.07416815e+00
 -4.58010364e-01  1.04004952e+00 -5.09567026e-01 -1.61622488e+00
 -6.12138187e-02 -5.31910787e-01 -5.26547365e-02  1.15474698e+00
 -3.44593982e-03 -1.09849887e+00  1.10428859e+00  1.09796001e+00
 -7.51511374e-01  1.04664547e-01 -7.74177047e-01  6.00585733e-01
  3.02381440e-01  9.48541351e-01 -9.90307549e-02 -1.79533891e+00
 -1.63406148e-01

In [123]:
answer = np.sort(ary)[::-1][ : int(0.05*len(ary))]
answer

array([2.59043436, 2.42555724, 2.39357801, 2.21727161, 1.95767994,
       1.93899672, 1.93877125, 1.75131805, 1.73288203, 1.67853187])

In [5]:
ary = np.array([[1,2,3,4],[100,89,90,79],[60,70,80,99]])
aryInfo(ary)
print()

print('두 번째 행을 국어점수로 생각하고 국어 점수를 기준으로 열을 정렬 ')
# case1
answer = ary[ : , ary[1].argsort()]
print(answer)
print()

# case2
answer = np.argsort(ary)[1][::-1]
print(answer)

type -  <class 'numpy.ndarray'>
shape -  (3, 4)
dimension -  2
dtype -  int32

data - 
[[  1   2   3   4]
 [100  89  90  79]
 [ 60  70  80  99]]

두 번째 행을 국어점수로 생각하고 국어 점수를 기준으로 열을 정렬 
[[  4   2   3   1]
 [ 79  89  90 100]
 [ 99  70  80  60]]

[0 2 1 3]
