In [1]:
import numpy as np
import pandas as pd

# 배열의 정보를 확인하기 위한 함수 정의

def aryInfo(ary) :
    print('type - ', type(ary))
    print('shape - ', ary.shape)
    print('dimension - ', ary.ndim)
    print('dtype - ', ary.dtype)
    print()
    print('data - ')
    print(ary)

- 난수: 정해진 알고리즘에 의해 특정한 숫자를 무작위로 만드는 것
- random 서브패키지를 이용해서 난수를 발생
- rand(): 균일분포 0~1 사이의 균일한 확률분포로 실수 난수를 생성하는 것
- randn(): 표준정규분포(실수)
- randint(): 균일분포 0~1 사이의 균일한 확률분포로 정수 난수를 생성하는 것

In [2]:
np.random.rand(10)

array([0.79756859, 0.00888705, 0.34753362, 0.49102923, 0.79428711,
       0.34940702, 0.48456826, 0.53078253, 0.85074455, 0.37155509])

In [3]:
np.random.rand(5)

array([0.62839423, 0.62064677, 0.67769459, 0.02878915, 0.04258879])

In [4]:
np.random.seed(100)  #seed를 설정하면 동일한 난수

In [5]:
np.random.rand(10)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [6]:
np.random.rand(5)

array([0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749])

In [7]:
np.random.seed(100)

In [8]:
np.random.rand(10)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [9]:
np.random.rand(5)

array([0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749])

In [10]:
np.random.rand(3,5)

array([[0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375],
       [0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045],
       [0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497]])

In [11]:
np.random.randn(3,5)

array([[ 1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869],
       [ 0.9370822 ,  0.73100034,  1.36155613, -0.32623806,  0.05567601],
       [ 0.22239961, -1.443217  , -0.75635231,  0.81645401,  0.75044476]])

In [12]:
np.random.randint(10, 20, size = 10)

array([13, 14, 17, 16, 13, 19, 10, 14, 14, 15])

In [14]:
np.random.randint(10,20, size=(3,5))

array([[17, 16, 16, 12, 14],
       [12, 17, 11, 16, 16],
       [10, 17, 12, 13, 15]])

- 데이터 샘플링
- choice(범위, 개수, p)

In [16]:
np.random.choice(5,10, p=[0.1, 0, 0.3, 0.6, 0])

array([0, 3, 3, 0, 3, 3, 2, 2, 3, 3])

In [17]:
print('문제) 동전을 20번 던져서 앞면(1)과 뒷면(0) 나오는 실험을 한다면? -')
np.random.choice(2,20, replace=True) #복원추출

문제) 동전을 20번 던져서 앞면(1)과 뒷면(0) 나오는 실험을 한다면? -


array([0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1])

In [18]:
np.random.randint(0, 2, 20)

array([1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1])

In [25]:
print('문제) 주사위를 100번 던져서 나오는 숫자의 평균?')
print(np.mean(np.random.randint(1, 6, 100)))

dice = np.random.choice(np.arange(1,7), 100, replace = True)
print('dice - ', np.mean(dice))

문제) 주사위를 100번 던져서 나오는 숫자의 평균?
3.27
dice -  3.48


In [30]:
#문제) 가격이 10,000원 주식이 있다. 이 주식의 일간 수익률(%)의 기대값이 0이고 
#표준편차가 1인 정규분포를 따른다고 했을 때 250일 동안의 주가를 무작위로 생성하고 싶다면?
price = 10000
price + (price*np.random.randn(250))/100

array([ 9971.17573052, 10037.52751708, 10004.20953186,  9991.00431597,
       10131.44282946,  9979.44780939,  9903.88814804,  9912.29202953,
        9965.0619461 , 10065.95634651, 10067.90203045,  9959.06260109,
        9964.66822719, 10042.93192866, 10134.87878683,  9972.71086438,
       10018.39363403, 10055.88657879,  9862.86767529,  9966.93561285,
       10045.22332724,  9946.94816856,  9971.8541781 ,  9935.58721261,
        9886.99737743,  9883.82334661, 10016.93330928,  9994.03018604,
       10110.58364466,  9933.81087241,  9964.14955627,  9992.88296499,
       10009.78638009, 10177.06682608, 10071.61109143,  9974.79653073,
       10166.81794413,  9916.65183546, 10116.51817812, 10016.82413857,
        9990.29802396,  9889.16283595, 10116.31257344,  9779.57730799,
        9987.66371228,  9956.08952808, 10062.99876168,  9913.04492935,
        9939.19189181, 10119.93328108, 10272.50208073, 10045.07629856,
        9916.05222756,  9995.98045247, 10088.50898919, 10158.60651416,
      

- 기후통계분석.csv 파일로드
- 문제) 기상관측 이래 서울의 최고기온이 가장 높았던 날짜 및 최고기온을 추출

In [34]:
raw_data = np.loadtxt('./data/numpy_data/기후통계분석.csv',
                     skiprows = 1,
                     dtype = 'U',
                     delimiter = ',')
aryInfo(raw_data)

type -  <class 'numpy.ndarray'>
shape -  (40414, 5)
dimension -  2
dtype -  <U10

data - 
[['1907-10-01' '108' '13.5' '7.9' '20.7']
 ['1907-10-02' '108' '16.2' '7.9' '22']
 ['1907-10-03' '108' '16.2' '13.1' '21.3']
 ...
 ['2021-08-23' '108' '22.4' '21' '24']
 ['2021-08-24' '108' '23.4' '21.1' '26.4']
 ['2021-08-25' '108' '25' '23.5' '27.3']]


In [35]:
print('type - ', type(raw_data[0]))
print('data - ', raw_data[0])

type -  <class 'numpy.ndarray'>
data -  ['1907-10-01' '108' '13.5' '7.9' '20.7']


In [37]:
temp = raw_data[:, 4]
print('type - ', type(temp))
print('data - ', temp)
print('dtype - ', temp.dtype)
temp = temp.astype(float)
print('dtype - ', temp.dtype)


type -  <class 'numpy.ndarray'>
data -  ['20.7' '22' '21.3' ... '24' '26.4' '27.3']
dtype -  <U10
dtype -  float64


In [40]:
np.argsort(temp)[::-1]

array([39293, 30520, 39292, ...,  2662,  8503,  2661], dtype=int64)

In [41]:
answer = raw_data[np.argsort(temp)[::-1]][0, :]
print(answer)

['2018-08-01' '108' '33.6' '27.8' '39.6']


In [ ]:
# --실습

In [73]:
rating_data = np.loadtxt('./data/numpy_data/ratings.dat',
                     skiprows = 1,
                     dtype = 'U',
                     delimiter = '::')
rating_data = rating_data.astype(np.int64)
aryInfo(rating_data)

# 데이터의 첫 5행만 확인
print(rating_data[0:5])

# 데이터의 형태 확인
print(type(rating_data))



type -  <class 'numpy.ndarray'>
shape -  (1000209, 4)
dimension -  2
dtype -  int64

data - 
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]
<class 'numpy.ndarray'>


In [87]:
# 전체 평균 평점 계산
score = rating_data[:,2]
print(np.mean(score))

3.581564453029317


In [123]:
user_ids = rating_data[:,0]
user_ids = np.unique(user_ids)
print(user_ids)

n=1
for user_id in user_ids:
    if user_id == n:
        print(score)
        n=n+1


[   1    2    3 ... 6038 6039 6040]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ...

[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ...

[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ...

[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ... 5 4 4]
[5 3 3 ...

In [133]:
seoul = np.loadtxt('./data/numpy_data/seoul.csv',
                     skiprows = 8,
                     dtype = 'U',
                     delimiter = ',')
aryInfo(seoul)

type -  <class 'numpy.ndarray'>
shape -  (40819, 5)
dimension -  2
dtype -  <U10

data - 
[['1907-10-01' '108' '13.5' '7.9' '20.7']
 ['1907-10-02' '108' '16.2' '7.9' '22']
 ['1907-10-03' '108' '16.2' '13.1' '21.3']
 ...
 ['2020-09-04' '108' '23.3' '19.9' '27.5']
 ['2020-09-05' '108' '23.3' '19.2' '27.3']
 ['2020-09-06' '108' '21.7' '19.5' '24.4']]


In [151]:
high = seoul[:,4]
print(high)
seoul[np.argsort(high)][0,:]

['20.7' '22' '21.3' ... '27.5' '27.3' '24.4']


array(['1952-12-16', '108', '', '', ''], dtype='<U10')

In [152]:
seoul[np.argsort(high)[::-1]][0,:]

# answer = raw_data[np.argsort(high)[::-1]][0, :]
# print(answer)

array(['2001-11-15', '108', '5.1', '0.7', '9.9'], dtype='<U10')